name: Check code formatting with Black

on:
  pull_request:
    paths:
      - '**.py'  # Only run if Python files change

permissions:
  contents: read

jobs:
  black-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # or match your project's version

      - name: Install black
        run: pip install black

      - name: Run black --check
        run: black --check --diff .
