jobs:
  update-cff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install cffr
        run: Rscript -e 'install.packages("cffr", repos="https://cloud.r-project.org")'

      - name: Update CITATION.cff
        run: |
          Rscript -e 'library(cffr); cff_gha_update(path=".", overwrite=FALSE)'
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git commit -am "chore: update CITATION.cff"
          git push
