name: Validate CITATION.cff

on:
  push:
    paths:
      - 'CITATION.cff'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate CITATION.cff
        uses: citation-file-format/cffconvert-github-action@v2
        with:
          args: "--validate"
